### ISSUE TITLE
是否能开启UDP？

### ISSUE THREAD

**Issue by iTaoPu** [XyHK-HUC/Colab#2]
内置转换中没有能开启UDP？不知道代码中能否写入

**Comment by XyHK-HUC** [comment]
大多数Shadowsocks客户端默认支持UDP，只要服务器端支持UDP转发，客户端应该能正常使用UDP流量，所以具体要看服务器支不支持UDP。

**Comment by iTaoPu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by iTaoPu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
