### ISSUE TITLE
403 Forbidden Access Denied  这是咋回事啊

### ISSUE THREAD

**Issue by flylj999** [XyHK-HUC/Colab#5]
403 Forbidden
Access Denied
 这是咋回事啊

**Comment by flylj999** [comment]
哦 好了，token得大写吧。不过怎么导入v2ray啊，我直接复制地址过去，好像没出来节点啊

**Comment by XyHK-HUC** [comment]
部署的既是订阅链接

**Comment by flylj999** [comment]
嗯 v2ray 导入不了，clashverge导入进去了，有ping但好像上不了网在 2024年12月15日，02:26，HiinEnkelte ***@***.***> 写道：﻿
部署的既是订阅链接

**Comment by XyHK-HUC** [comment]
哪个可以用就用哪个，建议使用nekobox等singbox内核的软件，xray不支持ss协议的节点
